spring:
  redis:
#    host: localhost
#    password: 123456
    host: localhost
    password: 123456.com
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1s
        min-idle: 0
        max-idle: 8
    database: 0
    timeout: 2000
  jooq:
    sql-dialect: mysql
    # 极简的配置
  quartz:
    scheduler-name: quartzScheduler
    overwrite-existing-jobs: true
    startup-delay: 3
    auto-startup: true
    wait-for-jobs-to-complete-on-shutdown: false
    # 内存存储job，无需配置jdbc
    job-store-type: memory
    # 额外的配置，可以不配
#    properties:
#      org:
#        quartz:
#          scheduler:
#            instanceName: clusteredScheduler
#            instanceId: AUTO
#          jobStore:
#            class: org.quartz.impl.jdbcjobstore.JobStoreTX
#            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
#            tablePrefix: QRTZ_
#            isClustered: true
#            clusterCheckinInterval: 10000
#            useProperties: false
#          threadPool:
#            class: org.quartz.simpl.SimpleThreadPool
#            threadCount: 10
#            threadPriority: 5
#            threadsInheritContextClassLoaderOfInitializingThread: true

debug: true

logging:
  path: ./log
  file: demo.log
  level:
#    root: WARN
#    root: DEBUG
    root: info
    org.springframework.web: DEBUG

server:
  port: 8088
  ssl:
    key-alias: chen_bq
#    yml根为项目根目录
    key-store: server.keystore
    key-password: 123456
    key-store-type: JKS
#    配置为false则不读取信息
    enabled: false


#jdbc2:
#  driverClassName: com.mysql.jdbc.Driver
#  url: jdbc:mysql://192.168.10.24:3306/opentogetdb?useUnicode=true&characterEncoding=utf8&jdbcCompliantTruncation=false&useSSL=false&serverTimezone=Asia/Shanghai
#  username: root
#  password: 123456


