/*
 * This file is generated by jOOQ.
 */
package com.example.demo.model.entity.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * 订单表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Order implements Serializable {

    private static final long serialVersionUID = 1079922381;

    private Integer    id;
    private String     outtradeno;
    private BigDecimal totalamount;
    private String     tradeno;
    private String     buyerlogonid;
    private String     receiptamount;
    private BigDecimal buyerpayamount;
    private Timestamp  gmtpayment;
    private String     fundchannel;
    private BigDecimal fundamount;
    private String     buyeruserid;
    private String     buyerid;
    private Integer    orderstatus;

    public Order() {}

    public Order(Order value) {
        this.id = value.id;
        this.outtradeno = value.outtradeno;
        this.totalamount = value.totalamount;
        this.tradeno = value.tradeno;
        this.buyerlogonid = value.buyerlogonid;
        this.receiptamount = value.receiptamount;
        this.buyerpayamount = value.buyerpayamount;
        this.gmtpayment = value.gmtpayment;
        this.fundchannel = value.fundchannel;
        this.fundamount = value.fundamount;
        this.buyeruserid = value.buyeruserid;
        this.buyerid = value.buyerid;
        this.orderstatus = value.orderstatus;
    }

    public Order(
        Integer    id,
        String     outtradeno,
        BigDecimal totalamount,
        String     tradeno,
        String     buyerlogonid,
        String     receiptamount,
        BigDecimal buyerpayamount,
        Timestamp  gmtpayment,
        String     fundchannel,
        BigDecimal fundamount,
        String     buyeruserid,
        String     buyerid,
        Integer    orderstatus
    ) {
        this.id = id;
        this.outtradeno = outtradeno;
        this.totalamount = totalamount;
        this.tradeno = tradeno;
        this.buyerlogonid = buyerlogonid;
        this.receiptamount = receiptamount;
        this.buyerpayamount = buyerpayamount;
        this.gmtpayment = gmtpayment;
        this.fundchannel = fundchannel;
        this.fundamount = fundamount;
        this.buyeruserid = buyeruserid;
        this.buyerid = buyerid;
        this.orderstatus = orderstatus;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @NotNull
    @Size(max = 128)
    public String getOuttradeno() {
        return this.outtradeno;
    }

    public void setOuttradeno(String outtradeno) {
        this.outtradeno = outtradeno;
    }

    public BigDecimal getTotalamount() {
        return this.totalamount;
    }

    public void setTotalamount(BigDecimal totalamount) {
        this.totalamount = totalamount;
    }

    @Size(max = 64)
    public String getTradeno() {
        return this.tradeno;
    }

    public void setTradeno(String tradeno) {
        this.tradeno = tradeno;
    }

    @Size(max = 100)
    public String getBuyerlogonid() {
        return this.buyerlogonid;
    }

    public void setBuyerlogonid(String buyerlogonid) {
        this.buyerlogonid = buyerlogonid;
    }

    @Size(max = 11)
    public String getReceiptamount() {
        return this.receiptamount;
    }

    public void setReceiptamount(String receiptamount) {
        this.receiptamount = receiptamount;
    }

    public BigDecimal getBuyerpayamount() {
        return this.buyerpayamount;
    }

    public void setBuyerpayamount(BigDecimal buyerpayamount) {
        this.buyerpayamount = buyerpayamount;
    }

    public Timestamp getGmtpayment() {
        return this.gmtpayment;
    }

    public void setGmtpayment(Timestamp gmtpayment) {
        this.gmtpayment = gmtpayment;
    }

    @Size(max = 32)
    public String getFundchannel() {
        return this.fundchannel;
    }

    public void setFundchannel(String fundchannel) {
        this.fundchannel = fundchannel;
    }

    public BigDecimal getFundamount() {
        return this.fundamount;
    }

    public void setFundamount(BigDecimal fundamount) {
        this.fundamount = fundamount;
    }

    @Size(max = 32)
    public String getBuyeruserid() {
        return this.buyeruserid;
    }

    public void setBuyeruserid(String buyeruserid) {
        this.buyeruserid = buyeruserid;
    }

    @Size(max = 32)
    public String getBuyerid() {
        return this.buyerid;
    }

    public void setBuyerid(String buyerid) {
        this.buyerid = buyerid;
    }

    public Integer getOrderstatus() {
        return this.orderstatus;
    }

    public void setOrderstatus(Integer orderstatus) {
        this.orderstatus = orderstatus;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Order (");

        sb.append(id);
        sb.append(", ").append(outtradeno);
        sb.append(", ").append(totalamount);
        sb.append(", ").append(tradeno);
        sb.append(", ").append(buyerlogonid);
        sb.append(", ").append(receiptamount);
        sb.append(", ").append(buyerpayamount);
        sb.append(", ").append(gmtpayment);
        sb.append(", ").append(fundchannel);
        sb.append(", ").append(fundamount);
        sb.append(", ").append(buyeruserid);
        sb.append(", ").append(buyerid);
        sb.append(", ").append(orderstatus);

        sb.append(")");
        return sb.toString();
    }
}
