/*
 * This file is generated by jOOQ.
 */
package com.example.demo.model.entity.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.Size;

import javax.annotation.Generated;
import javax.validation.constraints.Size;


/**
 * 会员表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = -1943820036;

    private Integer   userId;
    private String    userKey;
    private String    userName;
    private String    userOpenid;
    private String    userPassword;
    private String    userPhone;
    private Double    userAmount;
    private Double    userBalance;
    private Integer   userPoint;
    private Timestamp userBinddate;
    private Timestamp userBirth;
    private String    userEmail;
    private String    userGender;
    private String    userAddress;
    private Integer   userIsenabled;
    private Timestamp userLogindate;
    private String    userRemarks;
    private Integer   userUsetotal;
    private String    userUname;
    private String    userQdkey;
    private String    userCdkey;
    private String    userDevcode;
    private String    userSecondcdkey;
    private String    userFromtype;
    private Timestamp userJointime;
    private Timestamp userCreatetime;
    private Timestamp userUpdatetime;

    public User() {}

    public User(User value) {
        this.userId = value.userId;
        this.userKey = value.userKey;
        this.userName = value.userName;
        this.userOpenid = value.userOpenid;
        this.userPassword = value.userPassword;
        this.userPhone = value.userPhone;
        this.userAmount = value.userAmount;
        this.userBalance = value.userBalance;
        this.userPoint = value.userPoint;
        this.userBinddate = value.userBinddate;
        this.userBirth = value.userBirth;
        this.userEmail = value.userEmail;
        this.userGender = value.userGender;
        this.userAddress = value.userAddress;
        this.userIsenabled = value.userIsenabled;
        this.userLogindate = value.userLogindate;
        this.userRemarks = value.userRemarks;
        this.userUsetotal = value.userUsetotal;
        this.userUname = value.userUname;
        this.userQdkey = value.userQdkey;
        this.userCdkey = value.userCdkey;
        this.userDevcode = value.userDevcode;
        this.userSecondcdkey = value.userSecondcdkey;
        this.userFromtype = value.userFromtype;
        this.userJointime = value.userJointime;
        this.userCreatetime = value.userCreatetime;
        this.userUpdatetime = value.userUpdatetime;
    }

    public User(
        Integer   userId,
        String    userKey,
        String    userName,
        String    userOpenid,
        String    userPassword,
        String    userPhone,
        Double    userAmount,
        Double    userBalance,
        Integer   userPoint,
        Timestamp userBinddate,
        Timestamp userBirth,
        String    userEmail,
        String    userGender,
        String    userAddress,
        Integer   userIsenabled,
        Timestamp userLogindate,
        String    userRemarks,
        Integer   userUsetotal,
        String    userUname,
        String    userQdkey,
        String    userCdkey,
        String    userDevcode,
        String    userSecondcdkey,
        String    userFromtype,
        Timestamp userJointime,
        Timestamp userCreatetime,
        Timestamp userUpdatetime
    ) {
        this.userId = userId;
        this.userKey = userKey;
        this.userName = userName;
        this.userOpenid = userOpenid;
        this.userPassword = userPassword;
        this.userPhone = userPhone;
        this.userAmount = userAmount;
        this.userBalance = userBalance;
        this.userPoint = userPoint;
        this.userBinddate = userBinddate;
        this.userBirth = userBirth;
        this.userEmail = userEmail;
        this.userGender = userGender;
        this.userAddress = userAddress;
        this.userIsenabled = userIsenabled;
        this.userLogindate = userLogindate;
        this.userRemarks = userRemarks;
        this.userUsetotal = userUsetotal;
        this.userUname = userUname;
        this.userQdkey = userQdkey;
        this.userCdkey = userCdkey;
        this.userDevcode = userDevcode;
        this.userSecondcdkey = userSecondcdkey;
        this.userFromtype = userFromtype;
        this.userJointime = userJointime;
        this.userCreatetime = userCreatetime;
        this.userUpdatetime = userUpdatetime;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Size(max = 32)
    public String getUserKey() {
        return this.userKey;
    }

    public void setUserKey(String userKey) {
        this.userKey = userKey;
    }

    @Size(max = 64)
    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    @Size(max = 64)
    public String getUserOpenid() {
        return this.userOpenid;
    }

    public void setUserOpenid(String userOpenid) {
        this.userOpenid = userOpenid;
    }

    @Size(max = 32)
    public String getUserPassword() {
        return this.userPassword;
    }

    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    @Size(max = 20)
    public String getUserPhone() {
        return this.userPhone;
    }

    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }

    public Double getUserAmount() {
        return this.userAmount;
    }

    public void setUserAmount(Double userAmount) {
        this.userAmount = userAmount;
    }

    public Double getUserBalance() {
        return this.userBalance;
    }

    public void setUserBalance(Double userBalance) {
        this.userBalance = userBalance;
    }

    public Integer getUserPoint() {
        return this.userPoint;
    }

    public void setUserPoint(Integer userPoint) {
        this.userPoint = userPoint;
    }

    public Timestamp getUserBinddate() {
        return this.userBinddate;
    }

    public void setUserBinddate(Timestamp userBinddate) {
        this.userBinddate = userBinddate;
    }

    public Timestamp getUserBirth() {
        return this.userBirth;
    }

    public void setUserBirth(Timestamp userBirth) {
        this.userBirth = userBirth;
    }

    @Size(max = 255)
    public String getUserEmail() {
        return this.userEmail;
    }

    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    @Size(max = 4)
    public String getUserGender() {
        return this.userGender;
    }

    public void setUserGender(String userGender) {
        this.userGender = userGender;
    }

    @Size(max = 255)
    public String getUserAddress() {
        return this.userAddress;
    }

    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }

    public Integer getUserIsenabled() {
        return this.userIsenabled;
    }

    public void setUserIsenabled(Integer userIsenabled) {
        this.userIsenabled = userIsenabled;
    }

    public Timestamp getUserLogindate() {
        return this.userLogindate;
    }

    public void setUserLogindate(Timestamp userLogindate) {
        this.userLogindate = userLogindate;
    }

    @Size(max = 255)
    public String getUserRemarks() {
        return this.userRemarks;
    }

    public void setUserRemarks(String userRemarks) {
        this.userRemarks = userRemarks;
    }

    public Integer getUserUsetotal() {
        return this.userUsetotal;
    }

    public void setUserUsetotal(Integer userUsetotal) {
        this.userUsetotal = userUsetotal;
    }

    @Size(max = 64)
    public String getUserUname() {
        return this.userUname;
    }

    public void setUserUname(String userUname) {
        this.userUname = userUname;
    }

    @Size(max = 32)
    public String getUserQdkey() {
        return this.userQdkey;
    }

    public void setUserQdkey(String userQdkey) {
        this.userQdkey = userQdkey;
    }

    @Size(max = 32)
    public String getUserCdkey() {
        return this.userCdkey;
    }

    public void setUserCdkey(String userCdkey) {
        this.userCdkey = userCdkey;
    }

    @Size(max = 64)
    public String getUserDevcode() {
        return this.userDevcode;
    }

    public void setUserDevcode(String userDevcode) {
        this.userDevcode = userDevcode;
    }

    @Size(max = 32)
    public String getUserSecondcdkey() {
        return this.userSecondcdkey;
    }

    public void setUserSecondcdkey(String userSecondcdkey) {
        this.userSecondcdkey = userSecondcdkey;
    }

    @Size(max = 2)
    public String getUserFromtype() {
        return this.userFromtype;
    }

    public void setUserFromtype(String userFromtype) {
        this.userFromtype = userFromtype;
    }

    public Timestamp getUserJointime() {
        return this.userJointime;
    }

    public void setUserJointime(Timestamp userJointime) {
        this.userJointime = userJointime;
    }

    public Timestamp getUserCreatetime() {
        return this.userCreatetime;
    }

    public void setUserCreatetime(Timestamp userCreatetime) {
        this.userCreatetime = userCreatetime;
    }

    public Timestamp getUserUpdatetime() {
        return this.userUpdatetime;
    }

    public void setUserUpdatetime(Timestamp userUpdatetime) {
        this.userUpdatetime = userUpdatetime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(userId);
        sb.append(", ").append(userKey);
        sb.append(", ").append(userName);
        sb.append(", ").append(userOpenid);
        sb.append(", ").append(userPassword);
        sb.append(", ").append(userPhone);
        sb.append(", ").append(userAmount);
        sb.append(", ").append(userBalance);
        sb.append(", ").append(userPoint);
        sb.append(", ").append(userBinddate);
        sb.append(", ").append(userBirth);
        sb.append(", ").append(userEmail);
        sb.append(", ").append(userGender);
        sb.append(", ").append(userAddress);
        sb.append(", ").append(userIsenabled);
        sb.append(", ").append(userLogindate);
        sb.append(", ").append(userRemarks);
        sb.append(", ").append(userUsetotal);
        sb.append(", ").append(userUname);
        sb.append(", ").append(userQdkey);
        sb.append(", ").append(userCdkey);
        sb.append(", ").append(userDevcode);
        sb.append(", ").append(userSecondcdkey);
        sb.append(", ").append(userFromtype);
        sb.append(", ").append(userJointime);
        sb.append(", ").append(userCreatetime);
        sb.append(", ").append(userUpdatetime);

        sb.append(")");
        return sb.toString();
    }
}
