/*
 * This file is generated by jOOQ.
 */
package com.example.demo.model.entity.jooq.tables.records;


import com.example.demo.model.entity.jooq.tables.User;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.Size;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 会员表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> {

    private static final long serialVersionUID = -782226444;

    /**
     * Setter for <code>yhldb.user.user_id</code>. 主键
     */
    public void setUserId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>yhldb.user.user_id</code>. 主键
     */
    public Integer getUserId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>yhldb.user.user_key</code>. 外键
     */
    public void setUserKey(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>yhldb.user.user_key</code>. 外键
     */
    @Size(max = 32)
    public String getUserKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>yhldb.user.user_name</code>. 微信名
     */
    public void setUserName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>yhldb.user.user_name</code>. 微信名
     */
    @Size(max = 64)
    public String getUserName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>yhldb.user.user_openId</code>. 微信openid
     */
    public void setUserOpenid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>yhldb.user.user_openId</code>. 微信openid
     */
    @Size(max = 64)
    public String getUserOpenid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>yhldb.user.user_password</code>. 密码
     */
    public void setUserPassword(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>yhldb.user.user_password</code>. 密码
     */
    @Size(max = 32)
    public String getUserPassword() {
        return (String) get(4);
    }

    /**
     * Setter for <code>yhldb.user.user_phone</code>. 电话
     */
    public void setUserPhone(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>yhldb.user.user_phone</code>. 电话
     */
    @Size(max = 20)
    public String getUserPhone() {
        return (String) get(5);
    }

    /**
     * Setter for <code>yhldb.user.user_amount</code>. 消费金额
     */
    public void setUserAmount(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>yhldb.user.user_amount</code>. 消费金额
     */
    public Double getUserAmount() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>yhldb.user.user_balance</code>. 余额
     */
    public void setUserBalance(Double value) {
        set(7, value);
    }

    /**
     * Getter for <code>yhldb.user.user_balance</code>. 余额
     */
    public Double getUserBalance() {
        return (Double) get(7);
    }

    /**
     * Setter for <code>yhldb.user.user_point</code>. 积分
     */
    public void setUserPoint(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>yhldb.user.user_point</code>. 积分
     */
    public Integer getUserPoint() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>yhldb.user.user_bindDate</code>. 关注日期
     */
    public void setUserBinddate(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>yhldb.user.user_bindDate</code>. 关注日期
     */
    public Timestamp getUserBinddate() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>yhldb.user.user_birth</code>. 出生日期
     */
    public void setUserBirth(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>yhldb.user.user_birth</code>. 出生日期
     */
    public Timestamp getUserBirth() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>yhldb.user.user_email</code>. e-mail
     */
    public void setUserEmail(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>yhldb.user.user_email</code>. e-mail
     */
    @Size(max = 255)
    public String getUserEmail() {
        return (String) get(11);
    }

    /**
     * Setter for <code>yhldb.user.user_gender</code>. 性别
     */
    public void setUserGender(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>yhldb.user.user_gender</code>. 性别
     */
    @Size(max = 4)
    public String getUserGender() {
        return (String) get(12);
    }

    /**
     * Setter for <code>yhldb.user.user_address</code>. 地址
     */
    public void setUserAddress(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>yhldb.user.user_address</code>. 地址
     */
    @Size(max = 255)
    public String getUserAddress() {
        return (String) get(13);
    }

    /**
     * Setter for <code>yhldb.user.user_isEnabled</code>. 是否启用
     */
    public void setUserIsenabled(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>yhldb.user.user_isEnabled</code>. 是否启用
     */
    public Integer getUserIsenabled() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>yhldb.user.user_loginDate</code>. 最后登录日期
     */
    public void setUserLogindate(Timestamp value) {
        set(15, value);
    }

    /**
     * Getter for <code>yhldb.user.user_loginDate</code>. 最后登录日期
     */
    public Timestamp getUserLogindate() {
        return (Timestamp) get(15);
    }

    /**
     * Setter for <code>yhldb.user.user_remarks</code>. 备注信息
     */
    public void setUserRemarks(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>yhldb.user.user_remarks</code>. 备注信息
     */
    @Size(max = 255)
    public String getUserRemarks() {
        return (String) get(16);
    }

    /**
     * Setter for <code>yhldb.user.user_useTotal</code>. 用户次数
     */
    public void setUserUsetotal(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>yhldb.user.user_useTotal</code>. 用户次数
     */
    public Integer getUserUsetotal() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>yhldb.user.user_uname</code>. 用户姓名
     */
    public void setUserUname(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>yhldb.user.user_uname</code>. 用户姓名
     */
    @Size(max = 64)
    public String getUserUname() {
        return (String) get(18);
    }

    /**
     * Setter for <code>yhldb.user.user_qdKey</code>. 渠道key
     */
    public void setUserQdkey(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>yhldb.user.user_qdKey</code>. 渠道key
     */
    @Size(max = 32)
    public String getUserQdkey() {
        return (String) get(19);
    }

    /**
     * Setter for <code>yhldb.user.user_cdKey</code>. 场地key
     */
    public void setUserCdkey(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>yhldb.user.user_cdKey</code>. 场地key
     */
    @Size(max = 32)
    public String getUserCdkey() {
        return (String) get(20);
    }

    /**
     * Setter for <code>yhldb.user.user_devCode</code>. 设备号
     */
    public void setUserDevcode(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>yhldb.user.user_devCode</code>. 设备号
     */
    @Size(max = 64)
    public String getUserDevcode() {
        return (String) get(21);
    }

    /**
     * Setter for <code>yhldb.user.user_secondCdKey</code>. 二级场地key
     */
    public void setUserSecondcdkey(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>yhldb.user.user_secondCdKey</code>. 二级场地key
     */
    @Size(max = 32)
    public String getUserSecondcdkey() {
        return (String) get(22);
    }

    /**
     * Setter for <code>yhldb.user.user_fromType</code>. 用户来源，1微信2支付宝
     */
    public void setUserFromtype(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>yhldb.user.user_fromType</code>. 用户来源，1微信2支付宝
     */
    @Size(max = 2)
    public String getUserFromtype() {
        return (String) get(23);
    }

    /**
     * Setter for <code>yhldb.user.user_joinTime</code>. 加入时间
     */
    public void setUserJointime(Timestamp value) {
        set(24, value);
    }

    /**
     * Getter for <code>yhldb.user.user_joinTime</code>. 加入时间
     */
    public Timestamp getUserJointime() {
        return (Timestamp) get(24);
    }

    /**
     * Setter for <code>yhldb.user.user_createTime</code>. 创建时间
     */
    public void setUserCreatetime(Timestamp value) {
        set(25, value);
    }

    /**
     * Getter for <code>yhldb.user.user_createTime</code>. 创建时间
     */
    public Timestamp getUserCreatetime() {
        return (Timestamp) get(25);
    }

    /**
     * Setter for <code>yhldb.user.user_updateTime</code>. 更新时间
     */
    public void setUserUpdatetime(Timestamp value) {
        set(26, value);
    }

    /**
     * Getter for <code>yhldb.user.user_updateTime</code>. 更新时间
     */
    public Timestamp getUserUpdatetime() {
        return (Timestamp) get(26);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Integer userId, String userKey, String userName, String userOpenid, String userPassword, String userPhone, Double userAmount, Double userBalance, Integer userPoint, Timestamp userBinddate, Timestamp userBirth, String userEmail, String userGender, String userAddress, Integer userIsenabled, Timestamp userLogindate, String userRemarks, Integer userUsetotal, String userUname, String userQdkey, String userCdkey, String userDevcode, String userSecondcdkey, String userFromtype, Timestamp userJointime, Timestamp userCreatetime, Timestamp userUpdatetime) {
        super(User.USER);

        set(0, userId);
        set(1, userKey);
        set(2, userName);
        set(3, userOpenid);
        set(4, userPassword);
        set(5, userPhone);
        set(6, userAmount);
        set(7, userBalance);
        set(8, userPoint);
        set(9, userBinddate);
        set(10, userBirth);
        set(11, userEmail);
        set(12, userGender);
        set(13, userAddress);
        set(14, userIsenabled);
        set(15, userLogindate);
        set(16, userRemarks);
        set(17, userUsetotal);
        set(18, userUname);
        set(19, userQdkey);
        set(20, userCdkey);
        set(21, userDevcode);
        set(22, userSecondcdkey);
        set(23, userFromtype);
        set(24, userJointime);
        set(25, userCreatetime);
        set(26, userUpdatetime);
    }
}
